name: lean_file_picker_example
description: Demonstrates how to use the lean_file_picker plugin.
version: 0.0.1+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  lean_file_picker:
    # When depending on this package from a real application you should use:
    #   lean_file_picker: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
