name: lean_file_picker
description: Flutter package to pick a single file using the native file explorer.
version: 0.0.2
homepage: https://github.com/perron2/lean-file-picker

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ch.perron2.lean_file_picker
        pluginClass: LeanFilePickerPlugin
      ios:
        pluginClass: LeanFilePickerPlugin
